"""AI presenter video pipeline - single project CLI.

  python pipeline.py --project lesson-01                     # run / resume
  python pipeline.py --project lesson-01 --manual-video      # you supply clips in video/
  python pipeline.py --project lesson-01 --plan-only         # stop after scenes.json
  python pipeline.py --project lesson-01 --scene scene_005 --regenerate [--stage audio|video|render]
  python pipeline.py --project lesson-01 --review
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dotenv import load_dotenv

from services import ffmpeg, qa
from services.orchestrator import Pipeline, Printer, RunOptions
from services.project_manager import REPO_ROOT, ConfigError, Project
from utils.duration import fmt_seconds
from utils.retry import PipelineError
from utils.tls import use_system_certificates


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="AI presenter video production pipeline")
    ap.add_argument("--project", required=True, help="folder name under projects/")
    ap.add_argument("--resume", action="store_true",
                    help="continue from the last checkpoint (default behaviour; kept for clarity)")
    ap.add_argument("--replan", action="store_true", help="re-split the script (keeps media of unchanged scenes)")
    ap.add_argument("--plan-only", action="store_true", help="write scenes.json and stop")
    ap.add_argument("--manual-video", action="store_true", help="clips are generated by hand and placed in video/")
    ap.add_argument("--audio-provider", choices=["inworld", "mock"], help="override config audio.provider")
    ap.add_argument("--video-provider", choices=["gemini", "flow", "library", "mock", "manual"],
                    help="override config generation.provider")
    ap.add_argument("--scene", help="scene id, e.g. scene_005 (with --regenerate)")
    ap.add_argument("--regenerate", action="store_true", help="regenerate --scene")
    ap.add_argument("--stage", choices=["audio", "video", "render"], default="video",
                    help="what to regenerate for --scene (default: video)")
    ap.add_argument("--review", action="store_true", help="QA report for all scenes; generates nothing")
    ap.add_argument("--max-clips", type=int, help="generate at most N new video clips this run")
    return ap


def review(project: Project) -> int:
    state = project.load_state()
    if not state:
        print(f"No scenes planned yet for {project.name}.")
        return 1
    print(f"Review: {project.name}\n")
    problems = []
    for s in state["scenes"]:
        res = qa.check_scene(s, project.dir, project.config) if s["status"] == "complete" else None
        if res is None:
            mark = "x" if s["status"] == "failed" else "…"
        else:
            mark = {"ok": "✓", "warn": "⚠", "fail": "✗"}[res.status]
        print(f"  {s['id']} {mark}  {s['status']:<16} audio {fmt_seconds(s.get('actual_audio_duration')):>7}"
              f"  rendered {fmt_seconds(s.get('rendered_duration')):>7}")
        if res is None or res.status != "ok":
            problems.append((s, res))
    for s, res in problems:
        vids = []
        for v in s.get("video_files", []):
            try:
                vids.append(f"{v} ({ffmpeg.probe(project.abs(v)).duration:.2f}s)")
            except ffmpeg.FFmpegError:
                vids.append(f"{v} (unreadable)")
        print(f"\n--- {s['id']} ({s['status']}) ---")
        print(f"  audio:    {s.get('audio_file') or '-'} ({fmt_seconds(s.get('actual_audio_duration'))})")
        print(f"  video:    {', '.join(vids) or '-'}")
        print(f"  rendered: {s.get('rendered_file') or '-'}")
        print(f"  sync:     {s.get('sync')}")
        if s.get("error"):
            print(f"  error:    {s['error']}")
        if res:
            for e in res.errors:
                print(f"  ERROR:    {e}")
            for w in res.warnings:
                print(f"  WARNING:  {w}")
        print(f"  text:     {s['text']}")
        print(f"  action:   {s['visual_action']}")
        print(f"  regenerate: python pipeline.py --project {project.name} --scene {s['id']} --regenerate")
    print(f"\n{len(state['scenes']) - len(problems)}/{len(state['scenes'])} scenes OK")
    return 0 if not problems else 2


def run_project(name: str, args: argparse.Namespace, printer: Printer | None = None) -> dict:
    project = Project(name)
    cfg = project.config
    video = "manual" if args.manual_video else (args.video_provider or cfg.generation.provider)
    audio = args.audio_provider or cfg.audio.provider
    pipeline = Pipeline(project, audio_provider=audio, video_provider=video, printer=printer)
    return pipeline.run(RunOptions(replan=args.replan, plan_only=args.plan_only,
                                   regenerate_scene=args.scene if args.regenerate else None,
                                   regenerate_stage=args.stage, max_clips=args.max_clips))


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    load_dotenv(REPO_ROOT / ".env")
    use_system_certificates()
    args = build_parser().parse_args(argv)
    if args.regenerate and not args.scene:
        print("--regenerate needs --scene <scene_id>")
        return 2
    try:
        if args.review:
            return review(Project(args.project))
        report = run_project(args.project, args)
    except (ConfigError, PipelineError, ffmpeg.FFmpegError) as exc:
        print(f"\nERROR: {exc}")
        return 1
    except KeyboardInterrupt:
        print("\nInterrupted. Progress is saved; re-run the same command to resume.")
        return 130
    if report.get("stopped"):
        return 0
    return 0 if report.get("final_file") else 3


if __name__ == "__main__":
    sys.exit(main())
