"""Video provider interface plus mock, manual, clip-library and Gemini (Veo) implementations.

The pipeline only ever talks to `VideoProvider`; it does not know whether a clip came from
the Gemini API, a browser, a person, or a mock.
"""
from __future__ import annotations

import math
import mimetypes
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path

from services import ffmpeg
from services.config import GeminiConfig, GenerationConfig, SyncConfig, VideoConfig
from services.sync import plan_clip_durations
from utils.retry import PermanentError, RateLimitError, TransientError


@dataclass
class ClipRequest:
    prompt: str
    reference_image: Path          # first frame / identity reference
    duration: float
    output_path: Path
    last_frame_image: Path | None = None
    negative_prompt: str = ""
    seed: int | None = None
    label: str = ""                # scene id
    gesture: str = ""              # planned gesture id (library provider matches clips on it)
    dialogue: str = ""             # the narration line this clip should show being spoken


class ManualClipMissing(Exception):
    """Manual mode: the clip has not been supplied yet. Not a failure."""


class VideoProvider:
    name = "base"
    supports_last_frame = False
    uses_reference_image = True

    def __init__(self, generation: GenerationConfig):
        self.allowed_durations = list(generation.allowed_durations)

    def plan_durations(self, target: float, sync: SyncConfig) -> list[float]:
        """Clip lengths to request so the footage covers `target` seconds of narration."""
        return plan_clip_durations(target, self.allowed_durations, sync)

    def generate(self, request: ClipRequest) -> Path:
        raise NotImplementedError


class MockVideoProvider(VideoProvider):
    """Renders a real MP4 of the requested length from the presenter image (with an audio
    track that must be stripped). `fail_times` lets tests simulate provider failures."""

    name = "mock"
    supports_last_frame = True

    def __init__(self, generation: GenerationConfig, video: VideoConfig,
                 fail_times: dict[str, int] | None = None):
        super().__init__(generation)
        self.video = video
        self.fail_times = dict(fail_times or {})
        self.calls: list[ClipRequest] = []

    def generate(self, request: ClipRequest) -> Path:
        self.calls.append(request)
        key = request.output_path.stem
        if self.fail_times.get(key, 0) > 0:
            self.fail_times[key] -= 1
            raise TransientError(f"mock provider simulated failure for {key}")
        request.output_path.parent.mkdir(parents=True, exist_ok=True)
        ffmpeg.run(ffmpeg.build_test_clip_cmd(request.reference_image, request.duration,
                                              request.output_path, self.video, key), timeout=300)
        return request.output_path


class ManualVideoProvider(VideoProvider):
    """Clips are generated by a person (e.g. in Gemini / Flow) and dropped into video/."""

    name = "manual"
    supports_last_frame = False

    def __init__(self, generation: GenerationConfig, locate):
        super().__init__(generation)
        self._locate = locate  # callable(output_path) -> existing file or None

    def generate(self, request: ClipRequest) -> Path:
        found = self._locate(request.output_path)
        if found is None:
            raise ManualClipMissing(request.output_path.name)
        return found


class LibraryVideoProvider(VideoProvider):
    """Cuts each scene's footage from a reusable library of presenter clips (for example
    generated once in the Gemini app), so producing a lesson needs no video generation.

    Clip file names select gestures: `head_nod.mp4`, `head_nod_2.mp4` serve scenes planned
    with gesture "head_nod". Scenes whose gesture has no clip use the general pool, which
    excludes opening/closing clips. Consecutive scenes never get the same clip, and the
    window taken from a clip rotates so repeated clips do not look identical.
    """

    name = "library"
    uses_reference_image = False
    SPECIAL = ("welcome", "closing")  # only used for their own gesture

    def __init__(self, generation: GenerationConfig, library_dir: Path, video: VideoConfig):
        super().__init__(generation)
        from services.project_manager import VIDEO_EXTS
        self.library_dir = library_dir
        self.video = video
        files = sorted(f for f in library_dir.glob("*") if f.suffix.lower() in VIDEO_EXTS
                       and not f.name.startswith(("_", ".")) and f.stat().st_size > 0)             if library_dir.is_dir() else []
        if not files:
            raise PermanentError(f"No clips in {library_dir}. Generate them from PROMPTS.md in that folder.")
        self.clips: list[tuple[Path, float]] = []
        for f in files:
            info = ffmpeg.probe(f)
            if not info.has_video:
                raise PermanentError(f"Library clip has no video stream: {f}")
            self.clips.append((f, info.video_duration or info.duration))
        self.max_segment = max(1.0, min(d for _, d in self.clips) - 0.05)
        self._last: Path | None = None

    def plan_durations(self, target: float, sync: SyncConfig) -> list[float]:
        n = math.ceil(target / self.max_segment)
        return [round(target / n, 3)] * n

    @staticmethod
    def _matches(clip: Path, gesture: str) -> bool:
        return bool(gesture) and (clip.stem == gesture
                                  or re.fullmatch(rf"{re.escape(gesture)}_\d+", clip.stem) is not None)

    def _pick(self, gesture: str, seed: int) -> tuple[Path, float, bool]:
        """Returns (clip, length, matched_gesture). Never repeats the previous scene's clip."""
        matched = [c for c in self.clips if self._matches(c[0], gesture)]
        general = [c for c in self.clips if not any(self._matches(c[0], s) for s in self.SPECIAL)] or self.clips
        for pool, is_match in ((matched, True), (general, False), (self.clips, False)):
            fresh = [c for c in pool if c[0] != self._last]
            if fresh:
                clip = fresh[seed % len(fresh)]
                return clip[0], clip[1], is_match
        clip = self.clips[0]  # library of one clip: repetition is unavoidable
        return clip[0], clip[1], False

    def generate(self, request: ClipRequest) -> Path:
        m = re.search(r"(\d+)", request.label or request.output_path.stem)
        seed = (int(m.group(1)) if m else 0) * 7 + len(request.output_path.stem)
        path, length, matched = self._pick(request.gesture, seed)
        dur = min(request.duration, length)
        slack = max(0.0, length - dur)
        # A gesture clip's action is usually mid-clip: take the centre. Otherwise rotate windows.
        start = slack / 2 if matched else (0.0, slack / 2, slack)[seed % 3]
        request.output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = request.output_path.with_name(request.output_path.stem + ".part.mp4")
        ffmpeg.run(["ffmpeg", "-hide_banner", "-v", "error", "-y", "-ss", f"{start:.3f}", "-i", str(path),
                    "-t", f"{dur:.3f}", "-an", "-c:v", "libx264", "-preset", "veryfast", "-crf", "14",
                    "-pix_fmt", "yuv420p", str(tmp)], timeout=300)
        os.replace(tmp, request.output_path)
        self._last = path
        return request.output_path


class GeminiVideoProvider(VideoProvider):
    """Veo image-to-video through the Gemini API (google-genai SDK).

    Veo 3.1 accepts 4/6/8 second clips, 24 fps, always generates audio (we discard it),
    supports `last_frame` interpolation, and keeps outputs server-side for only 2 days,
    so every clip is downloaded immediately.
    """

    name = "gemini"
    supports_last_frame = True

    def __init__(self, generation: GenerationConfig, cfg: GeminiConfig):
        super().__init__(generation)
        self.generation = generation
        self.cfg = cfg
        self._client = None
        if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
            raise PermanentError("GEMINI_API_KEY is not set. Add it to .env, or run with --manual-video.")
        try:
            from google import genai  # noqa: F401
        except ImportError as exc:
            raise PermanentError("google-genai is not installed: venv\\Scripts\\pip install google-genai") from exc

    @property
    def client(self):
        if self._client is None:
            from google import genai
            self._client = genai.Client()
        return self._client

    @staticmethod
    def _image(path: Path):
        from google.genai import types
        mime = mimetypes.guess_type(path.name)[0] or "image/jpeg"
        return types.Image(image_bytes=path.read_bytes(), mime_type=mime)

    def _classify(self, exc: Exception, action: str) -> Exception:
        from google.genai import errors
        code = getattr(exc, "code", None)
        msg = f"Veo {action} failed: {exc}"
        if isinstance(exc, errors.APIError) and code is not None:
            if code == 429:
                return RateLimitError(
                    f"Veo {action} rejected: quota/rate limit (HTTP 429). Check that billing is enabled for the "
                    f"API key's Google project and your Veo limits at https://ai.dev/rate-limit")
            if code >= 500:
                return TransientError(msg)
            if code in (401, 403):
                return PermanentError(msg + " Check GEMINI_API_KEY and Veo access on your account.")
            return PermanentError(msg)
        return TransientError(msg)

    def generate(self, request: ClipRequest) -> Path:
        from google.genai import types

        if request.duration not in self.allowed_durations:
            raise PermanentError(f"Veo duration {request.duration}s not in {self.allowed_durations}")
        config = types.GenerateVideosConfig(
            aspect_ratio=self.generation.aspect_ratio,
            duration_seconds=int(request.duration),
            resolution=self.cfg.resolution,
            number_of_videos=1,
            negative_prompt=request.negative_prompt or None,
            person_generation=self.cfg.person_generation,
            last_frame=self._image(request.last_frame_image) if request.last_frame_image else None,
            seed=request.seed,
        )
        try:
            op = self.client.models.generate_videos(
                model=self.cfg.model, prompt=request.prompt,
                image=self._image(request.reference_image), config=config,
            )
        except Exception as exc:  # noqa: BLE001
            raise self._classify(exc, "request") from exc

        deadline = time.monotonic() + self.cfg.timeout_seconds
        while not op.done:
            if time.monotonic() > deadline:
                raise TransientError(f"Veo generation timed out after {self.cfg.timeout_seconds:.0f}s")
            time.sleep(self.cfg.poll_interval_seconds)
            try:
                op = self.client.operations.get(op)
            except Exception as exc:  # noqa: BLE001
                raise self._classify(exc, "status poll") from exc

        if op.error:
            raise TransientError(f"Veo generation error: {op.error}")
        response = op.response or op.result
        videos = getattr(response, "generated_videos", None) or []
        if not videos:
            reasons = getattr(response, "rai_media_filtered_reasons", None)
            if reasons:
                raise PermanentError(f"Veo safety filter blocked the clip: {reasons}. Adjust the prompt/image.")
            raise TransientError("Veo returned no video")
        try:
            request.output_path.parent.mkdir(parents=True, exist_ok=True)
            tmp = request.output_path.with_name(request.output_path.stem + ".part.mp4")
            self.client.files.download(file=videos[0].video, destination=tmp)
            os.replace(tmp, request.output_path)
        except Exception as exc:  # noqa: BLE001
            raise self._classify(exc, "download") from exc
        return request.output_path
